### ISSUE TITLE
In Licenses tab How add if Available licenses is Increase. We required adding provision

### ISSUE THREAD

**Issue by irshad-basha-shaik** [irshad-basha-shaik/assets#2]

**Comment by swamy0075** [comment]
Not Completed. Not showing De
![PIC3](https://user-images.githubusercontent.com/98141614/184291840-87a006a7-6b44-4321-9505-0c9c06ab85ef.PNG)
tails.

**Comment by swamy0075** [comment]
Not Completed. Not showing Details.
![PIC3](https://user-images.githubusercontent.com/98141614/184291973-783a94eb-ffaf-442c-a1cf-601bcfd94201.PNG)
